.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SSREPI\.SH" "" "October 2022" "" ""
.
.SH "NAME"
\fBssrepi\.sh\fR \- interface libary for SSREPI
.
.SH "SYNOPSIS"
The library for doing (Social Simulation REPository Interface) SSREPI provenance and metadata collection
.
.SH "DESCRIPTION"
The following calls are available in Bash > 4\.0\.
.
.SH "SSREPI_application"
.
.SH "SSREPI_argument"
.
.SH "SSREPI_call"
.
.SH "SSREPI_content"
.
.SH "SSREPI_contributor"
.
.SH "SSREPI_hutton_person"
.
.SH "SSREPI_implements"
.
.SH "SSREPI_input"
.
.SH "SSREPI_invoke"
.
.SH "SSREPI_involvement"
.
.SH "SSREPI_make_tag"
.
.SH "SSREPI_me"
.
.SH "SSREPI_output"
.
.SH "SSREPI_paper"
.
.SH "SSREPI_parameter"
.
.SH "SSREPI_person"
.
.SH "SSREPI_person_makes_assumption"
.
.SH "SSREPI_pipeline"
.
.SH "SSREPI_project"
.
.SH "SSREPI_require_exact"
.
.SH "SSREPI_require_minimum"
.
.SH "SSREPI_set"
.
.SH "SSREPI_statistical_method"
.
.SH "SSREPI_statistical_variable"
.
.SH "SSREPI_statistics"
.
.SH "SSREPI_study"
.
.SH "SSREPI_tag"
.
.SH "SSREPI_value"
.
.SH "SSREPI_variable"
.
.SH "SSREPI_visualisation"
.
.SH "SSREPI\evisualisation_method"
.
.SH "SSREPI\evisualisation_variable"
.
.SH "ENVRIONMENT VARIABLES"
SSREPI_NOF_CPUS=2 SSREPI_SLURM
.
.SH "AUTHORS"
Doug Salt, Lorenzo Milazzo, Gary Polhill
.
.SH "REPORTING BUGS"
.
.SH "COPYRIGHT"
Copyright © 2022 The James Hutton Institute\. License GPLv3+: GNU GPL version 3 or later \fIhttps://gnu\.org/licenses/gpl\.html\fR\.
.
.P
This is free software: you are free to change and redistribute it\. There is NO WARRANTY, to the extent permitted by law\.
.
.SH "SEE ALSO"
.
.SH "STANDARDS"
.
.SH "HISTORY"

