.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "CONTAINERTYPES" "" "January 2023" "" ""
.
.SH "SYNOPSIS"
Some blurb
.
.SH "DESCRIPTION"
.
.SH "CLASSES"
.
.SS "InvalidEntity(Exception):"
.
.SS "Table:"
.
.SS "Application:"
.
.SS "Argument:"
.
.SS "ArgumentValue:"
.
.SS "Assumption:"
.
.SS "Assumption:"
.
.SS "Computer:"
.
.SS "Container:"
.
.SS "ContainerType:"
.
.SS "Content:"
.
.SS "Context:"
.
.SS "Contributor:"
.
.SS "Dependency:"
.
.SS "Documentation:"
.
.SS "Employs:"
.
.SS "Entailment:"
.
.SS "Implements:"
.
.SS "Input:"
.
.SS "Involvement:"
.
.SS "Meets:"
.
.SS "Model:"
.
.SS "Parameter:"
.
.SS "Person:"
.
.SS "PersonalData:"
.
.SS "Pipeline:"
.
.SS "Process:"
.
.SS "Product:"
.
.SS "Project:"
.
.SS "Requirement:"
.
.SS "Specification:"
.
.SS "StatisticalInput:"
.
.SS "StatisticalMethod:"
.
.SS "StatisticalVariable:"
.
.SS "Statistics:"
.
.SS "Study:"
.
.SS "Tag:"
.
.SS "TagMap:"
.
.SS "User:"
.
.SS "Uses:"
.
.SS "Value:"
.
.SS "Variable:"
.
.SS "Visualisation:"
.
.SS "VisualisationMethod:"
.
.SS "VisualisationValue:"
.
.SS "InvalidDBSpec:"
.
.SS "InvalidNode:"
.
.SS "InvalidEdge:"
.
.SH "FUNCTIONS"
.
.SS "dict_factory(cursor, row):"
.
.SS "connect_db(working_dir):"
Will connect to either a sqlite3 or postgres database\.
.
.SS "disconnect_db(conn):"
.
.SS "create_tables(conn):"
.
.SS "set_debug(value):"
.
.SS "write_all_to_db(ss_rep, conn, order = None):"
.
.SS "initially_populate_db(ssrep_array):"
.
.SS "studies_table_exists(conn):"
.
.SS "print_values(ssr_dict):"
.
.SS "is_positive_int(s):"
.
.SS "iso8601(str):"
.
.SS "ip(str):"
.
.SS "mimetype(allowableMimeTypes):"
.
.SS "graph():"
.
.SS "derive_edges():"
.
.SS "derive_edge(schema):"
.
.SS "labels():"
.
.SS "get_label(schema):"
.
.SS "get_nodes(conn, nodes, labels):"
.
.SS "draw_nodes(conn, graph, nodes, labels):"
.
.SS "format_text(text, length=30):"
.
.SS "get_edges(conn, edges, activeNodes):"
.
.SS "remove_orphans(nodes, edges):"
.
.SS "remove_edges(nodes,edges):"
.
.SS "save_dot(nodes, edges, output=None):"
.
.SS "draw_graph (conn, nodes, output):"
.
.SH "OPTIONS"
.
.SH "ENVRIONMENT"
.
.SH "EXIT STATUS"
.
.SH "RETURN VALUE"
.
.SH "EXAMPLES"
.
.SH "FILES"
.
.SH "AUTHORS"
Doug Salt, Lorenzo Milazzo, Gary Polhill
.
.SH "REPORTING BUGS"
.
.SH "BUGS"
.
.SH "COPYRIGHT"
Copyright © 2022 The James Hutton Institute\. License GPLv3+: GNU GPL version 3 or later \fIhttps://gnu\.org/licenses/gpl\.html\fR\.
.
.P
This is free software: you are free to change and redistribute it\. There is NO WARRANTY, to the extent permitted by law\.
.
.SH "SEE ALSO"
.
.SH "HISTORY"

