.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SSREPI\.SH" "" "February 2023" "" ""
.
.SH "NAME"
\fBssrepi\.sh\fR \- interface libary for SSREPI
.
.SH "SYNOPSIS"
Some blurb
.
.SH "DESCRIPTION"
.
.SH "OPTIONS"
.
.SH "ENVRIONMENT"
.
.SH "EXIT STATUS"
.
.SH "RETURN VALUE"
.
.SH "EXAMPLES"
.
.SH "FILES"
.
.SH "AUTHORS"
Doug Salt, Lorenzo Milazzo, Gary Polhill
.
.SH "REPORTING BUGS"
.
.SH "BUGS"
.
.SH "COPYRIGHT"
Copyright © 2022 The James Hutton Institute\. License GPLv3+: GNU GPL version 3 or later \fIhttps://gnu\.org/licenses/gpl\.html\fR\.
.
.P
This is free software: you are free to change and redistribute it\. There is NO WARRANTY, to the extent permitted by law\.
.
.SH "SEE ALSO"
.
.SH "HISTORY"

